version: "3.9"

services:
  mysql:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_SCHEMA}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    networks:
      - app-tier
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  app-tier:
    driver: bridge

volumes:
  mysql-data: null
